version: '2.24.5'

services:
  api-nest-lm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-lm
    ports:
      - '3000:3000'

  db-postgres-lm:
    image: postgres:16.2
    restart: always
    container_name: postgres-lm
    ports:
      - '5435:5432'
    volumes:
      - ./db-lm:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: dblm

  pgadmin-lm:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4-lm
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'

networks:
  default:
    name: nest-postgres-networks

volumes:
  postgres-lm:
  pgadmin-lm:
